"use client";

import { jsPDF } from "jspdf";
import type { Profile } from "./types";

export function downloadAdvisorPdf(input: {
  profile: Partial<Profile>;
  summaryText: string;
  generatedDate: string; // ISO date string
}): void {
  const { profile, summaryText, generatedDate } = input;

  const doc = new jsPDF({ unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 20;
  const marginRight = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = 20;

  // ── Helpers ──────────────────────────────────────────────────────────────────

  function checkPageBreak(neededHeight: number): void {
    if (y + neededHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
  }

  function addText(
    text: string,
    options: { fontSize?: number; bold?: boolean; indent?: number } = {}
  ): void {
    const { fontSize = 10, bold = false, indent = 0 } = options;
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");

    const x = marginLeft + indent;
    const maxWidth = contentWidth - indent;
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    const lineHeight = fontSize * 0.4; // approx mm per pt at standard DPI

    checkPageBreak(lines.length * lineHeight + 2);
    doc.text(lines, x, y);
    y += lines.length * lineHeight + 2;
  }

  function addSectionHeader(title: string): void {
    y += 4;
    checkPageBreak(10);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, marginLeft, y);
    y += 5;
    // Underline
    doc.setLineWidth(0.3);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 4;
  }

  function addLabelValue(label: string, value: string): void {
    doc.setFontSize(10);
    const labelText = `${label}: `;
    doc.setFont("helvetica", "bold");
    const labelWidth = doc.getTextWidth(labelText);
    doc.setFont("helvetica", "normal");

    const valueLines = doc.splitTextToSize(
      value,
      contentWidth - labelWidth
    ) as string[];
    const lineHeight = 10 * 0.4;

    checkPageBreak(valueLines.length * lineHeight + 2);

    // Draw label bold
    doc.setFont("helvetica", "bold");
    doc.text(labelText, marginLeft, y);
    // Draw value normal on the same first line
    doc.setFont("helvetica", "normal");
    doc.text(valueLines[0], marginLeft + labelWidth, y);
    y += lineHeight + 1;

    // Remaining wrapped lines (indented past label)
    for (let i = 1; i < valueLines.length; i++) {
      checkPageBreak(lineHeight + 1);
      doc.text(valueLines[i], marginLeft + labelWidth, y);
      y += lineHeight + 1;
    }
  }

  // ── Header ───────────────────────────────────────────────────────────────────

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Advisor Summary", marginLeft, y);
  y += 9;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Tax Compass", marginLeft, y);
  y += 6;

  doc.setFontSize(10);
  doc.text(`Date: ${generatedDate}`, marginLeft, y);
  y += 10;

  // Horizontal rule below header
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 6;

  // ── Section 1 — Profile Details ───────────────────────────────────────────

  addSectionHeader("1. Profile Details");

  const val = (v: unknown): string =>
    v !== undefined && v !== null && v !== "" ? String(v) : "-";

  // Jurisdiction
  addLabelValue("Jurisdiction", val(profile.jurisdiction));

  // Assessment Year
  addLabelValue("Assessment Year", val(profile.assessmentYear));

  // Income Types
  const incomeTypes = profile.incomeTypes;
  const enabledIncomes =
    incomeTypes
      ? (Object.keys(incomeTypes) as Array<keyof typeof incomeTypes>)
          .filter((k) => incomeTypes[k])
          .join(", ")
      : "";
  addLabelValue("Income Types", enabledIncomes || "-");

  // Advisor context fields
  const ac = profile.advisorContext;
  addLabelValue("Visa Type", val(ac?.visaType));
  addLabelValue(
    "Tax Resident Elsewhere",
    val(ac?.taxResidentElsewhere)
  );
  addLabelValue(
    "Citizenships",
    ac?.citizenships?.length ? ac.citizenships.join(", ") : "-"
  );
  addLabelValue(
    "Files Tax Elsewhere",
    ac?.filesTaxElsewhere !== undefined ? (ac.filesTaxElsewhere ? "Yes" : "No") : "-"
  );
  addLabelValue(
    "Company Director",
    ac?.isCompanyDirector !== undefined
      ? ac.isCompanyDirector
        ? "Yes"
        : "No"
      : "-"
  );
  addLabelValue(
    "Permanent Home in Jurisdiction",
    val(ac?.permanentHomeInJurisdiction)
  );

  // Employment fields
  const emp = profile.employment;
  addLabelValue("Employment: Foreign Employer", val(emp?.foreignEmployer));
  addLabelValue(
    "Employment: Salary Borne by Local Entity",
    val(emp?.salaryBorneByLocalEntity)
  );
  addLabelValue(
    "Employment: Worked While in Jurisdiction",
    val(emp?.workedWhileInJurisdiction)
  );

  // Trips
  const tripCount = profile.presence?.trips?.length ?? 0;
  addLabelValue("Trips logged", String(tripCount));

  // ── Section 2 — Situation Summary ─────────────────────────────────────────

  addSectionHeader("2. Situation Summary");

  addText(summaryText || "-", { fontSize: 10 });

  // ── Footer disclaimer ─────────────────────────────────────────────────────

  y += 8;
  checkPageBreak(20);

  // Thin rule above footer
  doc.setLineWidth(0.3);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 5;

  const disclaimer =
    "This document was generated by Tax Compass based on user-provided information and AI-generated analysis. " +
    "It is intended as a preparation summary for professional consultation and does not constitute tax or legal advice.";

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth) as string[];
  checkPageBreak(disclaimerLines.length * 4);
  doc.text(disclaimerLines, marginLeft, y);

  // ── Trigger download ──────────────────────────────────────────────────────

  const datePart = generatedDate.slice(0, 10); // YYYY-MM-DD
  doc.save(`advisor-summary-${datePart}.pdf`);
}
